apiVersion: v1
kind: Pod
metadata:
  name: mnist-with-device-plugin
  labels:
    app: mnist-with-device-plugin
spec:
  containers:
  - name: mnist-with-device-plugin
    image: cargo.caicloud.io/cenph/mnist_softmax:1.0
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
    securityContext:
        privileged: true
