apiVersion: v1
kind: Pod
metadata:
  name: stub-device-plugin-test
  labels:
    app: stub-device-plugin-test
spec:
  restartPolicy: Always
  containers:
  - name: stub-device-plugin-test
    image: busybox
    command: ["sleep", "3000"]
    resources:
      requests:
        resource.name/1: 1
      limits:
        resource.name/1: 1
    securityContext:
        privileged: true
