apiVersion: v1
kind: Service
metadata:
  name: tf-gpu-test
  labels:
    run: tf-gpu-test
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    run: tf-gpu-test
